[icons]
cava = ""
code-oss = ""
discord = "ﭮ"
emacs = ""
feh = ""
firefox = ""
firefox-esr = ""
float_calc = ""
float_calcurse = ""
inkscape = ""
"org.inkscape.Inkscape" = ""
java = ""
julia = ""
jetbrains-idea = ""
jetbrains-toolbox = ""
lf = ""
musescore = "ﭻ"
mpv = ""
ncmpcpp = "ﱘ"
nmtui = ""
nvim = ""
pavucontrol = ""
python = ""
ranger = ""
slack = ""
spotify = ""
st = ""
sxiv = ""
xterm = ""
ytop = ""
zathura = ""
"org.pwmt.zathura" = ""
zoom = ""

[aliases]

[general]
separator = " "
# default_icon = ""
default_icon = "_"

[options]
remove_duplicates = false
use_instance = true
no_names = true
