[icons]
_default = "_"
cava = ""
code-oss = ""
discord = "ﭮ"
emacs = ""
feh = ""
firefox = ""
firefox-esr = ""
float_calc = ""
float_calcurse = ""
inkscape = ""
java = ""
julia = ""
jetbrains-idea = ""
jetbrains-toolbox = ""
lf = ""
musescore = "ﭻ"
mpv = ""
ncmpcpp = "ﱘ"
nmtui = ""
nvim = ""
pavucontrol = ""
python = ""
ranger = ""
slack = ""
spotify = ""
st = ""
sxiv = ""
xterm = ""
ytop = ""
zathura = ""
zoom = ""

[aliases]

[general]
separator = " "
