#!/bin/sh

# Internal: alsa_output.pci-0000_00_1f.3.analog-stereo
# External: alsa_output.pci_0000_00_1f.3.hdmi-stereo

xrandr | grep -q 'eDP-1 connected' && compton --config ~/.config/compton.conf.intel &
xrandr | grep -q 'DP-0 connected' && compton --config ~/.config/compton.conf.nvidia &
