#!/bin/sh

# General audio interface

[ -z "$2" ] && num="2" || num="$2"

case "$1" in
	u*) pulsemixer --change-volume +"$num" ;;
	d*) pulsemixer --change-volume -"$num" ;;
	m*) pulsemixer --toggle-mute ;;
	play) mpc play ;;
	n*) mpc next ;;
	prev) mpc prev ;;
	t*) mpc toggle ;;
	p*) mpc pause ;;
	r*) mpc seek 0% ;;
esac

pkill -RTMIN+10 i3blocks
pkill -RTMIN+11 i3blocks
