#!/bin/sh

# Command aliases
alias e='$EDITOR' \
    se='sudo "$EDITOR"' \
    f='$FILE' \
    sf='sudo "$FILE"' \
    ssc='sudo systemctl' \
    sdn='shutdown -h now' \
    ls='ls -hN --color=auto --group-directories-first' \
    grep='grep --color=auto' \
    diff='diff --color=auto' \
    upd='yay -Syu' \
    ytdl='youtube-dl -f bestaudio --extract-audio --audio-format mp3 --audio-quality 0' \
    wttr='curl wttr.in\/Cleveland' \
    tt='trash-put' \
    tem='trash-empty' \
    tls='trash-list' \
    tre='trash-restore' \
    trm='trash-rm' \
    edpon='xrandr --output eDP1 --auto' \
    edpoff='xrandr --output eDP1 --off' \
    glg='glxinfo | egrep "OpenGL vendor|OpenGL renderer"'

# Directory shortcuts
alias h='cd ~/' \
    d='cd ~/Documents/' \
    D='cd ~/Downloads/' \
    m='cd ~/Music/' \
    p='cd ~/Pictures/' \
    P='cd ~/Projects/' \
    cf='cd ~/.config/' \
    lb='cd ~/.local/bin/' \
    lt='cd ~/.local/Trash/'

# Config file shortcuts
alias cfp='"$EDITOR" ~/.zprofile' \
    cfs='"$EDITOR" ~/.zshrc' \
    cfx='"$EDITOR" ~/.xinitrc' \
    cfr='"$EDITOR" ~/.Xresources' \
    cfv='"$EDITOR" ~/.config/nvim/init.vim' \
    cfi='"$EDITOR" ~/.config/i3/config' \
    cfb='"$EDITOR" ~/.config/polybar/config' \
    cff='"$EDITOR" ~/.config/fontconfig/fonts.conf' \
    cfa='"$EDITOR" ~/.config/aliasrc'

# School directory shortcuts
alias 293='cd ~/Documents/-Fall2019/EECS-293/' \
    325='cd ~/Documents/-Fall2019/EECS-325/' \
    341='cd ~/Documents/-Fall2019/EECS-341/' \
    343='cd ~/Documents/-Fall2019/DSCI-343/' \
    398='cd ~/Documents/-Fall2019/ENGL-398/'

calc() { echo "$1" | bc -l ;}

# Vim -> Neovim
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

vf() { fzf | xargs -r -I % $EDITOR % ;}

# TLP battery charging thresholds
setb() { sudo tlp setcharge "$1" "$2" BAT0 ;}
clrb() { sudo tlp setcharge ;}
