#!/bin/sh

# Command aliases
alias cp="cp -v" \
    mv="mv -v" \
    rm="rm -vI" \
    ls='ls -hN --color=auto --group-directories-first' \
    grep='grep --color=auto'
    diff='diff --color=auto' \

alias e='$EDITOR' \
    se='sudoedit' \
    f='$FILE' \
    sf='sudo $FILE' \
    sc='systemctl' \
    ssc='sudo systemctl' \
    sdn='shutdown -h now' \
    hst='$EDITOR "$ZSH_CACHE_DIR"/.zsh_history' \
    upd='yay -Syu' \
    magit='nvim -c MagitOnly'
    ytdl='youtube-dl -f bestaudio --extract-audio --audio-format mp3 --audio-quality 0' \
    wttr='curl wttr.in' \
    tt='trash-put' \
    tem='trash-empty' \
    tls='trash-list' \
    tre='trash-restore' \
    trm='trash-rm' \
    glg='glxinfo | egrep "OpenGL vendor|OpenGL renderer"' \
    jlab='jupyter lab'

# Directory shortcuts
alias h='cd ~/' \
    d='cd ~/Documents/' \
    D='cd ~/Downloads/' \
    m='cd ~/Music/' \
    p='cd ~/Pictures/' \
    P='cd ~/Projects/' \
    cf='cd ~/.config/' \
    lb='cd ~/.local/bin/'

# Config file shortcuts
alias cfp='$EDITOR $ZDOTDIR/.zprofile' \
    cfs='$EDITOR $ZDOTDIR/.zshrc' \
    cfx='$EDITOR ~/.xinitrc' \
    cfr='$EDITOR ~/.Xresources' \
    cfv='$EDITOR ~/.config/nvim/init.vim' \
    cfi='$EDITOR ~/.config/i3/config' \
    cfb='$EDITOR ~/.config/polybar/config' \
    cff='$EDITOR ~/.config/fontconfig/fonts.conf' \
    cfa='$EDITOR ~/.config/aliasrc'

# School directory shortcuts

calc() { echo "$1" | bc -l ;}

# Vim -> Neovim
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

vf() { fzf | xargs -r -I % $EDITOR % ;}

# TLP battery charging thresholds
setb() { sudo tlp setcharge "$1" "$2" BAT0 ;}
chrg() { sudo tlp chargeonce ;}
clrb() { sudo tlp setcharge ;}
