#!/bin/sh

# Command aliases
alias cp="cp -v" \
    mv="mv -v" \
    rm="rm -vI" \
    ls='exa' \
    ll='exa -lah' \
    grep='grep --color=auto' \
    diff='diff --color=auto'

alias e='$EDITOR' \
    se='sudoedit' \
    f='$FILE' \
    sf='sudo $FILE' \
    sx='startx ~/.xinitrc' \
    sxi='startx ~/.xinitrc i3' \
    sxx='startx ~/.xinitrc xmonad' \
    sc='systemctl' \
    ssc='sudo systemctl' \
    sdn='sudo shutdown -h now' \
    h='history' \
    zup='zgen update' \
    magit='nvim -c MagitOnly' \
    tt='trash-put' \
    tem='trash-empty' \
    tls='trash-list | sort' \
    tre='trash-restore' \
    trm='trash-rm' \
    glx='glxinfo | grep "server glx vendor string"' \
    omi='optimus-manager --switch intel' \
    omn='optimus-manager --switch nvidia' \
    sps='sudo prime-switch' \
    xr='xmonad --recompile && xmonad --restart' \
    wttr='curl wttr.in' \
    jlab='jupyter lab' \
    ytdl='youtube-dl -f bestaudio --extract-audio --audio-format mp3 --audio-quality 0' \
    ytdl4='youtube-dl -f "bestaudio[ext=m4a]"' \
    ytdl4e='youtube-dl -f "bestaudio[ext=m4a]" --embed-thumbnail' \
    yarn="yarn --use-yarnrc $XDG_CONFIG_HOME/yarn/config"

# Directory shortcuts
alias d='cd ~/Documents/' \
    D='cd ~/Downloads/' \
    m='cd ~/Music/' \
    p='cd ~/Pictures/' \
    P='cd ~/Projects/' \
    re='cd ~/Repos/' \
    cf='cd ~/.config/' \
    lb='cd ~/.local/bin/'

# Config file shortcuts
alias cfp='$EDITOR $ZDOTDIR/.zprofile' \
    cfs='$EDITOR $ZDOTDIR/.zshrc' \
    cfx='$EDITOR ~/.xinitrc' \
    cfr='$EDITOR ~/.Xresources' \
    cfv='$EDITOR ~/.config/nvim/init.vim' \
    cfi='$EDITOR ~/.config/i3/config' \
    cfb='$EDITOR ~/.config/polybar/config' \
    cff='$EDITOR ~/.config/fontconfig/fonts.conf' \
    cfa='$EDITOR ~/.config/aliasrc'

# Vim -> Neovim
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

vf() { fzf | xargs -r -I % $EDITOR % ;}

# TLP battery charging thresholds
setb() { sudo tlp setcharge "$1" "$2" BAT0 ;}
chrg() { sudo tlp chargeonce ;}
clrb() { sudo tlp setcharge ;}
