#!/bin/sh

getcolor() {
    colorname="\.color$1:"
    xrdb -query | grep "$colorname" | awk '{print $NF}'
}

# Get colors from Xresources
DARKBLACK=$(getcolor 0)
# DARKRED=$(getcolor 1)
# DARKGREEN=$(getcolor 2)
# DARKYELLOW=$(getcolor 3)
DARKBLUE=$(getcolor 4)
DARKMAGENTA=$(getcolor 5)
# DARKCYAN=$(getcolor 6)
# DARKWHITE=$(getcolor 7)
# BLACK=$(getcolor 8)
# RED=$(getcolor 9)
# GREEN=$(getcolor 10)
# YELLOW=$(getcolor 11)
# BLUE=$(getcolor 12)
# MAGENTA=$(getcolor 13)
# CYAN=$(getcolor 14)
# WHITE=$(getcolor 15)

if [ "$(current-display)" = "$INTERNAL_INTEL" ]; then
    bspc monitor "$INTERNAL_INTEL" -d 1
else
    # TODO avoid hardcoding
    bspc monitor "eDP-1-1" -d 1
    bspc monitor "DP-1" -d 2
    bspc monitor "DP-0" -d 3
fi

bspc config normal_border_color "$DARKBLACK"
bspc config active_border_color "$DARKBLACK"
bspc config focused_border_color "$DARKBLUE"
bspc config presel_feedback_color "$DARKMAGENTA"
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config pointer_follows_monitor true
bspc config ignore_ewmh_focus true

bspc config window_gap 10
bspc config border_width 1

bspc rule -a Zathura state=tiled
bspc rule -a 'St:float_calc:*' state=floating
bspc rule -a 'St:float_calcurse:*' state=floating
bspc rule -a 'St:float_mixer:*' state=floating
bspc rule -a 'St:float_scratchpad:*' state=floating

pkill -x sxhkd; sxhkd &
$GOPATH/bin/btops &
launch-polybar bspwm &
