#!/bin/sh

case $BLOCK_BUTTON in
    1) pavucontrol ;;
    3) volctl mute ;;
    4) volctl up 2 ;;
    5) volctl down 2 ;;
esac

if [ $(pulsemixer --get-mute) -eq 1 ]; then
    vol="~"
else
    vol=$(pulsemixer --get-volume | awk '{print $1 "%"}')
fi

printf "%s" "$vol"
